---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    run_list:
      - recipe[galaxy::change-apt]

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[galaxy::default]
      #- recipe[galaxy::dev_tools]
      - recipe[galaxy::nginx]
      #- recipe[galaxy::java-1.7]
    attributes:
      java:
        install_flavor: "openjdk"
        jdk_version: 7
      galaxy:
        config: "config/galaxy.ini"
        reference: "latest_15.07"
        #reference: "latest_2014.08.11"
        #overwrite_run_sh: true
        #overwrite_fetch_eggs_py: true

        galaxy_ini:
          admin_users: "admin@galaxy.org"
          tool_dependency_dir: "./tool_dependency_directory"
          allow_library_path_paste: "True"
          cleanup_job: "onsuccess"
